added 1st workflow

diff --git a/.github/workflows/01-building-blocks.yml b/.github/workflows/01-building-blocks.yml
--- a/.github/workflows/01-building-blocks.yml
+++ b/.github/workflows/01-building-blocks.yml
@@ -1,20 +1,18 @@
-name:  01-Building Block
-on:  push
+name: 01-Building Blocks1
+on: push
 jobs:
   echo-hello:
-    runs-on:  ubuntu-latest
+    runs-on: ubuntu-latest
     steps:
-      -name:  Say Hello
-       run:  echo "Hello world"
+      - name: Say Hello
+        run: echo "Hello world"
 
   echo-bye:
-    runs-on:  ubuntu-latest
+    runs-on: ubuntu-latest
     steps:
-      -name:  Failed Step
-       run:|
-        echo  "I will fail"
-        exit 1
-      -name:  Say Good bye 
-       run:  echo "good Bye "
-
-
+      - name: Failed Step
+        run: |
+          echo "I will fail"
+          exit 1
+      - name: Say Good Bye
+        run: echo "Good Bye"
