added 1st workflow

diff --git a/.github/workflows/01-building-blocks.yml b/.github/workflows/01-building-blocks.yml
--- a/.github/workflows/01-building-blocks.yml
+++ b/.github/workflows/01-building-blocks.yml
@@ -7,3 +7,14 @@ jobs:
       -name: Say Hello
        run: echo "Hello world"
 
+  echo-bye:
+    runs-on: ubuntu-latest
+    steps:
+      -name: Failed Step
+       run:|
+        echo "I will fail"
+        exit 1
+      -name: Say Good bye 
+       run: echo "good Bye"
+
+
