added 1st workflow

diff --git a/.github/workflows/02-test.yaml b/.github/workflows/02-test.yaml
--- a/.github/workflows/02-test.yaml
+++ b/.github/workflows/02-test.yaml
@@ -1,2 +1,18 @@
-name:
-  on: push
+name: 01-Building Blocks2
+on: push
+jobs:
+  echo-hello:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Say Hello
+        run: echo "Hello world"
+
+  echo-bye:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Failed Step
+        run: |
+          echo "I will fail"
+          exit 1
+      - name: Say Good Bye
+        run: echo "Good Bye"
